### PR TITLE
Add EPUB3 docs to navigation bar

### PR DESCRIPTION
**Pull request by slonopotamus**
@mojavelinux not sure whether you want this to be alphabetically sorted or by popularity. I went the latter route.

### CODE REVIEW

**Comment by slonopotamus** [comment]
Also, do you want `<small>Ruby</small>` to be added?

**Comment by mojavelinux** [comment]
Yep, that looks good. Except can you add the language modifier `<small>Ruby</small>`?

**Comment by mojavelinux** [comment]
Oops, our comments crossed paths. Yes to your question.

**Comment by slonopotamus** [comment]
Done :)

**Pull request merged**
