### PR TITLE
Integrate asciidoctor-tabs

### PR DESCRIPTION
**Pull request by abelsromero**
UI update for https://github.com/asciidoctor/docs.asciidoctor.org/pull/82.

I was able to build and validate a local build of the docs with this, all working fine.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Nice work.

Let's put the tabs.js script directly after the site.js script. No need to wait until all the other auxiliary scripts have loaded. site.js always needs to be first, but tabs.js can be prioritized after that.

**Comment by mojavelinux** [comment]
I think you're missing the dependency on @asciidoctor/tabs in package.json. It should be a devDependency.

**Comment by abelsromero** [comment]
Thanks, applied the changes and the build is now working.

**Comment by abelsromero** [comment]
@mojavelinux sorry to bother, anything else I am missing?

**Comment by mojavelinux** [comment]
I think we're good. I'll review and merge as soon as I get a focused work session.

**Comment by mojavelinux** [comment]
Looks great!

**Pull request merged**
