### PR TITLE
resolves #46 enable search on mobile

### LINKED ISSUE #46: Search bar should be visible on mobile
Being able to search on mobile would be really beneficial since navigation is a bit more difficult than on desktop. So, being able to jump between pages using the search would provide a better experience on mobile.

Here's a rough draft:

102711115-a33c0480-42b7-11eb-8366-da0bf3894cc1

In the above screenshot, I've also replace the hamburger menu with an explicit "Menu" button but we can leave it for another issue.

### PR DESCRIPTION
**Pull request by mojavelinux**
- assign fixed height to search box on mobile
- make max height of search results account for height of search box
- configure search results to span width of screen on mobile
- configure search results to have width of 28rem on larger screens

### CODE REVIEW

**Comment by mojavelinux** [comment]
@Mogztter to review, you'll need to test locally. we really need to get some sort of test search working for the deploy preview.

The bundled styles for docsearch make the results look quirky on mobile. I don't know why they do it that way, but it's rather tedious to override. If you can figure it out, feel free to propose a follow-up fix.

**Comment by Mogztter** [comment]
> to review, you'll need to test locally. we really need to get some sort of test search working for the deploy preview.

Yes, that would be great. Currently, I'm using the Algolia index of docs.asciidoctor.org.

> The bundled styles for docsearch make the results look quirky on mobile. I don't know why they do it that way, but it's rather tedious to override. If you can figure it out, feel free to propose a follow-up fix.

Indeed, for reference here's what I'm seeing:

ok1

I cannot push on your branch/pull request but I made a small changes:

up

Commit: https://github.com/Mogztter/asciidoctor-docs-ui/commit/50be2a5dcf69d87319117b6012114c32110d0d83

**Comment by mojavelinux** [comment]
Thanks! You should be able to push a new commit now.

**Comment by mojavelinux** [comment]
Actually, I found some styles I did for a client that are close to this, but have a few more tweaks. I'm going to apply those to get effectively the same result.

**Comment by mojavelinux** [comment]
@Mogztter I see the issue with the input box size now. Thanks for pointing that out. I think I fixed it.

**Comment by mojavelinux** [comment]
Now that this is done, we need a new issue to rethink the search experience (UX) on mobile.

**Pull request merged**
