### PR TITLE
resolves #36 allow to copy multiple commands and command with line continuation

### LINKED ISSUE #36: Copy to clipboard does not capture entire multiline command or multiple commands
If the command in a console listing block spans multiple lines using a continuation, only the first line is captured. The copy button should capture a command that is continued.

Additionally, if there are multiple commands in the same block, then only the first command is taken. All the commands in the block should be captured and they should be joined using either `;` or `&&`.

### PR DESCRIPTION
**Pull request by Mogztter**
I'm using the same code on the Neo4j documentation UI.
Since this is a pure function, I wrote unit tests (see: https://github.com/neo4j-documentation/docs-ui/blob/master/src/specs/test.code.js) but I'm not sure how to automate them in the Gulp build.
Have you already thought about testing in the docs UI?

### CODE REVIEW

**Comment by mojavelinux** [comment]
I think this can be reduced to a single rx. (even simpler if we had matchAll, but c'est la vie)

```js
var commandRx = /^\$ \S[^\\\n]*(\\\n[^$][^\n]*)*(?=\n|$)/gm
let match
const cmds = []
while ((match = rx.exec(cmd))) cmds.push(match[0].substr(2).replace(/ *\\\n/, ' '))
text = cmds.join('\n')
```

I don't think the commands need to be separated by a semi-colon. And endline does the same thing and is easier for the user to go back to. We could keep the line continuations but in this code I decided to flatten them.

**Comment by mojavelinux** [comment]
> Have you already thought about testing in the docs UI?

Not yet. It's still a problem we need to solve in Antora.

**Comment by Mogztter** [comment]
> I think this can be reduced to a single rx. (even simpler if we had matchAll, but c'est la vie)

I'm fine using a rx. I can copy and paste your code or you can directly push a commit on my branch I don't mind.

>  don't think the commands need to be separated by a semi-colon. And endline does the same thing and is easier for the user to go back to.

Yes but it will actually run the command on paste. I don't expect the command to run on paste and when it does I'm always a bit shocked/scared (because I like to read the command one last time before pressing "Enter") but it might be just me :sweat_smile: 

> We could keep the line continuations but in this code I decided to flatten them.

I think it's fine :+1: 

> Not yet. It's still a problem we need to solve in Antora.

I'm looking forward to it :wink:

**Comment by Mogztter** [comment]
About testing, should I add something to unit test this logic?
Basically what I have in mind is to check if we are running in a Node environment (`module.exports` is available) and, if so, export a function named `copyableCommand`. I can then `require` the JavaScript file and write a unit test with Mocha + Chai.

**Comment by mojavelinux** [comment]
I pushed an update. I like your point about the deferred execution. That makes sense.

**Comment by mojavelinux** [comment]
I don't think adding testing for this function is really necessary. It's adding too much complexity to the build for something that is rarely going to change once we get it working. And there are far more important things to test, so I'd rather look at the testing problem as a whole rather than to patch something in.

I do like your idea about how to test these pure functions and it's something we should consider for an Antora UI test harness. Though I'm really not 100% comfortable until we are testing in the browser since that's where most of the problems originate.

**Comment by mojavelinux** [comment]
Perhaps we should join on `&&` instead of `;`. If you do run the command, you don't want it to continue if something is failing. And why would we give them commands we expect to fail?

**Comment by Mogztter** [comment]
> Perhaps we should join on && instead of ;. If you do run the command, you don't want it to continue if something is failing. And why would we give them commands we expect to fail?

I agree :+1:

**Pull request merged**
