### PR TITLE
resolves #48 always keep the site title on the header

### LINKED ISSUE #48: The site title should be visible on mobile
Currently, on mobile, the site title is hidden which might be a bit confusing.

Usually, the site title allows to go back to the home page but currently only the Asciidoctor logo is visible on mobile. I think that users will be tempted to click on the Asciidoctor logo to go back to the documentation site home (where in fact they will be redirected to https://asciidoctor.org).

102711115-a33c0480-42b7-11eb-8366-da0bf3894cc1

### PR DESCRIPTION
**Pull request by Mogztter**
| Mobile | Desktop |
| ------ | ------- |
|header | header-desktop |

resolves #48

### CODE REVIEW

**Comment by mojavelinux** [comment]
This is a good start. However, it doesn't account for the presence of the search box. As written, the CSS relies on the search box being a sibling child in the nav-start. Now it's the only child. The CSS needs to be updated to address the nav-item for the search box as a the last-child (instead of the sibling selector). Though we may want to consider whether nav-start should even be added when the search is disabled.

**Comment by Mogztter** [comment]
Doh! I completely forgot to enable the search 😅

**Comment by Mogztter** [comment]
@mojavelinux I removed `navbar-start` completely and added an explicit "search" class on the navigation bar item to hide it when the screen size is < 1024px.

**Comment by mojavelinux** [comment]
Based on the definitions at https://bulma.io/documentation/components/navbar/, I agree the navbar-start is not needed in our layout. I like the use of the CSS class to target specific items, since the first-child/last-child stuff was a bit obtuse.

I integrated the logic I just pushed to main to make the search box shrink to fit within the available space when space gets scarce.

I think this is now ready to go. Please verify that it works as you expect it to and I'll merge.

**Comment by mojavelinux** [comment]
(Ignore the merge conflicts. I'm going to squash, at which point they will go away).

**Comment by mojavelinux** [comment]
cc @Mogztter

**Comment by Mogztter** [comment]
@mojavelinux LGTM :ok_hand:

**Comment by mojavelinux** [comment]
Let's go!

**Pull request merged**
